# Generated by Django 3.2.7 on 2021-10-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaid_app', '0003_id_board_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='instagram_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawling_date', models.CharField(max_length=100)),
                ('insta_id', models.CharField(max_length=100)),
                ('follower', models.CharField(max_length=100)),
                ('following', models.CharField(max_length=100)),
                ('media_type', models.CharField(max_length=100)),
                ('post_link', models.CharField(max_length=255)),
                ('post_date', models.CharField(max_length=100)),
                ('caption', models.TextField()),
                ('like_cnt', models.CharField(max_length=100)),
                ('comments_cnt', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
    ]
